### PR TITLE
Language selector

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

- Add language selector button
- Add default language for country profiles

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

Screen Shot 2020-02-26 at 7 46 16 AM
Screen Shot 2020-02-26 at 7 46 21 AM
Screen Shot 2020-02-26 at 7 49 37 AM
Screen Shot 2020-02-26 at 7 49 43 AM
Screen Shot 2020-02-26 at 7 50 01 AM

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by karimkawambwa** [comment]
@kilemensi ping

**Comment by karimkawambwa** [comment]
@nerdlet ping

**Comment by karimkawambwa** [comment]
@kilemensi am fine with either or, i am not too familiar with the differences. Will have to find some in depth justification between to two to really have an opinion here so @KhadijaMahanga its your call.

*So should we revert ?*

>Language to me is something that's best as a query param and not part of path i.e. it modifies the resource at a given path and not return a different resource.

**Comment by KhadijaMahanga** [comment]
@karimkawambwa yes let's revert.

**Comment by DavidLemayian** [comment]
Agreed on using `En` (`English` in dropdown), `Fr` (`French` in dropdown) instead of flags. Some more reading on this - https://uxdesign.cc/my-take-on-language-selectors-945caceb58f7

**Pull request merged**
